apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "setae-api.fullname" . }}
  labels:
    {{- include "setae-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "setae-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "setae-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "setae-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          env:
              # The base image by default will use the number of available cores to create the worker processes.
              # This will be a very high number by default when deployed in the cluster!
              # See '/gunicorn_conf.py' on base image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
            - name: WORKERS_PER_CORE
              value: ".05"
            - name: OKAPI_URL
              valueFrom:
                secretKeyRef:
                  key: OKAPI_URL
                  name: db-connect-modules
            - name: OKAPI_TENANT
              valueFrom:
                secretKeyRef:
                  key: TENANT_ID
                  name: db-connect-modules
            - name: OKAPI_USER
              valueFrom:
                secretKeyRef:
                  key: OKAPI_READONLY_APP_USER
                  name: db-connect-modules
            - name: OKAPI_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: OKAPI_READONLY_APP_PASSWORD
                  name: db-connect-modules
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
